
#
# Configuration file for Travis CI
# https://travis-ci.org/
#

language: java

jdk:
  - openjdk11
  - openjdk13
  - openjdk15
  - oraclejdk11
  - oraclejdk13
  - oraclejdk15

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

script:
 - mvn test -B -DargLine="-Xmx8G"

after_success:
  - mvn clean cobertura:cobertura coveralls:report

sudo: false


