
#
# Configuration file for Travis CI
# http://travis-ci.org/
#

language: java

jdk:
  - oraclejdk8

before_install:
 - echo ${JAVA_OPTS}
 - export JAVA_OPTS=-Xmx8G
 - echo ${JAVA_OPTS}

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

after_success:
  - mvn clean cobertura:cobertura coveralls:report

sudo: false


