
#
# Configuration file for Travis CI
# http://travis-ci.org/
#

language: java

jdk:
  - oraclejdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

before_script:
 - export JAVA_OPTS=-Xmx8G

script:
 - mvn test -B -DargLine="-Xmx8G"

after_success:
  - mvn clean cobertura:cobertura coveralls:report

sudo: false


